### PR TITLE
Add ReSharper settings file to the repository

### PR DESCRIPTION
**Pull request by rukekre**
## What was the problem/requirement? (What/Why)
To make the ReSharper settings file available to all contributors of the Ambit plugin.

## What was the solution? (How)
Added the ReSharper settings file and a relevant README with the installation and usage instructions.

## What artifacts are related to this change?
Issues:  P56990807

## What is the impact of this change?
N/A

## Are you adding any new dependencies to the system?
No

## How were these changes tested?
Locally

----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rukekre** [comment]
Currently blocked. Pending investigation upon @brhook-aws return

**Review by brhook-aws — CHANGES_REQUESTED** [review]
`.editorsettings` should be changed to `.editorconfig`

**Comment by rukekre** [comment]
PR is ready for review again. @brhook-aws @kris-work

**Review by brhook-aws — APPROVED** [review]
Please have at least one more person review the changes, as my local may not be clean.

**Review by kris-work — APPROVED** [review]

**Review by haozhao-aws — APPROVED** [review]

**Pull request merged**
